version: 2.1

description: Delta ESLint Reports

orbs:
  dscar: naokikimura/dscar@0.6.2

executors:
  default:
    description: Default analysis execution environment
    parameters:
      docker-image:
        description: Specify the image used to execute the analysis
        type: string
        default: circleci/node
      resource_class:
        description: Amount of CPU and RAM allocated to each container in a job.
        type: string
        default: small
    docker:
      - image: << parameters.docker-image >>
    resource_class: << parameters.resource_class >>

commands:
  analyze:
    description: Analyze code statically using ESLint
    parameters:
      starting-points:
        description: Specify the path of starting to search for files to analyze (Multiple paths can be specified by separating them with line feed)
        type: string
        default: "."
      analysis-arguments:
        description: Arguments of eslint command
        type: string
        default: --ext .js,.jsx,.ts,.tsx
      no-analysis-output-timeout:
        description: Elapsed time the command can run without output. The string is a decimal with unit suffix, such as “20m”, “1.25h”, “5s”
        type: string
        default: 10m
      prepare:
        description: Specify the required steps before analysis if necessary
        type: steps
        default:
          - run: sudo npm install --global eslint
      redirecting-output:
        description: Specify "/dev/null" if you do not want to display the analysis results on the standard output
        type: enum
        enum: ["/dev/stdout", "/dev/stderr", "/dev/null"]
        default: "/dev/null"
    steps:
      - dscar/analyze:
          step-name: Analyze code statically using ESLint
          prepare: << parameters.prepare >>
          analysis-command: npx
          analysis-arguments: eslint << parameters.analysis-arguments >> -f checkstyle
          starting-points: << parameters.starting-points >>
          no-output-timeout: << parameters.no-analysis-output-timeout >>
          redirecting-output: << parameters.redirecting-output >>
  execute:
    description: Calculate the difference of ESLint results between HEAD branch and BASE branch
    parameters:
      has-reconstructed:
        description: Specify true if `compare-url/reconstruct` has not been executed yet
        type: boolean
        default: false
      attach-compare-url-workspace:
        description: "Attach a workspace for this command to use? Useful when `compare-url` orb's `reconstruct` job is called upstream in a given workflow"
        type: boolean
        default: false
      analyze:
        description: Specify analysis steps
        type: steps
        default:
          - analyze:
              prepare: []
      analysis-results-path:
        description: Specify the path to save the analysis results if you need to change it
        type: string
        default: "/tmp/analysis-results"
      calculate:
        description: Specify the steps for calculating the difference
        type: steps
        default:
          - dscar/calculate
      project-path:
        description: "Absolute path to your project's base directory, necessary for running git commands (default: job’s working_directory)"
        type: string
        default: ""
    steps:
      - run: sudo npm install --global eslint
      - dscar/execute:
          has-reconstructed: << parameters.has-reconstructed >>
          attach-compare-url-workspace: << parameters.attach-compare-url-workspace >>
          analysis-name: ESLint
          analyze: << parameters.analyze >>
          analysis-results-path: << parameters.analysis-results-path >>
          calculate: << parameters.calculate >>
          project-path: << parameters.project-path >>

jobs:
  analyze:
    description: Analyze code statically using ESLint
    parameters:
      executor:
        description: Specify the image used to execute analysis
        type: executor
        default: default
      is-target-branch-base:
        description: Check-out the BASE branch if true is specified
        type: boolean
        default: false
      has-reconstructed:
        description: Specify true if `compare-url/reconstruct` has not been executed yet
        type: boolean
        default: false
      attach-compare-url-workspace:
        description: "Attach a workspace for this command to use? Useful when `compare-url` orb's `reconstruct` job is called upstream in a given workflow"
        type: boolean
        default: false
      analyze:
        description: Specify analysis steps
        type: steps
        default:
          - analyze
      analysis-results-path:
        description: Specify the path to save the analysis results if you need to change it
        type: string
        default: "/tmp/analysis-results"
      test-results-path:
        description: Specify the value of the path parameter in the store_test_results step if you need to change it
        type: string
        default: "/tmp/test-results"
    executor: << parameters.executor >>
    steps:
      - dscar/set-result-path:
          analysis-name: ESLint
          analysis-results-path: << parameters.analysis-results-path >>
          is-target-branch-base: << parameters.is-target-branch-base >>
      - dscar/checkout-analysis-target:
          is-target-branch-base: << parameters.is-target-branch-base >>
          has-reconstructed: << parameters.has-reconstructed >>
          attach-compare-url-workspace: << parameters.attach-compare-url-workspace >>
      - steps: << parameters.analyze >>
      - when:
          condition: << parameters.test-results-path >>
          steps:
            - dscar/transform:
                analysis-name: ESLint
                analysis-results-path: << parameters.analysis-results-path >>
                test-results-path: << parameters.test-results-path >>
            - store_test_results:
                path: << parameters.test-results-path >>
  calculate:
    description: |
      Calculate the difference between the analysis results

      Use the [checkstyle-reports-combiner][1] command to calculate the difference

      [1]: https://www.npmjs.com/package/junit-reports-combiner
    parameters:
      executor:
        description: Specify the image used to execute analysis
        type: executor
        default: default
      calculate:
        description: Specify the steps for calculating the difference
        type: steps
        default:
          - dscar/calculate
      analysis-results-path:
        description: Specify the path to save the analysis results if you need to change it
        type: string
        default: "/tmp/analysis-results"
      test-results-path:
        description: Specify the value of the path parameter in the store_test_results step if you need to change it
        type: string
        default: "/tmp/test-results"
    executor: << parameters.executor >>
    steps:
      - dscar/set-analysis-result-paths:
          analysis-name: ESLint
          analysis-results-path: << parameters.analysis-results-path >>
      - steps: << parameters.calculate >>
      - dscar/transform:
          analysis-name: ESLint
          analysis-results-path: << parameters.analysis-results-path >>
          test-results-path: << parameters.test-results-path >>
          pattern: '.*/DELTA-analysis-results\.xml$'
      - store_test_results:
          path: << parameters.test-results-path >>
  execute:
    description: Calculate the difference of ESLint results between HEAD branch and BASE branch
    parameters:
      executor:
        description: Specify the image used to execute analysis
        type: executor
        default: default
      has-reconstructed:
        description: Specify true if `compare-url/reconstruct` has not been executed yet
        type: boolean
        default: false
      attach-compare-url-workspace:
        description: "Attach a workspace for this command to use? Useful when `compare-url` orb's `reconstruct` job is called upstream in a given workflow"
        type: boolean
        default: false
      analyze:
        description: Specify analysis steps
        type: steps
        default:
          - analyze:
              prepare: []
      analysis-results-path:
        description: Specify the path to save the analysis results if you need to change it
        type: string
        default: "/tmp/analysis-results"
      calculate:
        description: Specify the steps for calculating the difference
        type: steps
        default:
          - dscar/calculate
      test-results-path:
        description: Specify the value of the path parameter in the store_test_results step if you need to change it
        type: string
        default: "/tmp/test-results"
    executor: << parameters.executor >>
    steps:
      - execute:
          has-reconstructed: << parameters.has-reconstructed >>
          attach-compare-url-workspace: << parameters.attach-compare-url-workspace >>
          analyze: << parameters.analyze >>
          analysis-results-path: << parameters.analysis-results-path >>
          calculate: << parameters.calculate >>
      - dscar/transform:
          analysis-name: ESLint
          analysis-results-path: << parameters.analysis-results-path >>
          test-results-path: << parameters.test-results-path >>
          pattern: '.*/DELTA-analysis-results\.xml$'
      - store_test_results:
          path: << parameters.test-results-path >>
